version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  blazorapp:
    # Instead of building the image locally, we reference a pre-built image.
    # You would replace this with the name of your image on a registry like Docker Hub.
    image: "yourusername/yourblazorapp:latest"
    container_name: blazorapp
    ports:
      - "5000:80"
    depends_on:
      - mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
