version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  blazorapp:
    build:
      context: .
      dockerfile: BlazorApp/Dockerfile
    container_name: blazorapp
    ports:
      - "5000:8080" # Changed to 8080 to match the Dockerfile EXPOSE
    depends_on:
      - mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
